export const UPDATE_CARDS_STATE = 'UPDATE_CARDS_STATE';
export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const EDIT_CARD_DETAILS = 'EDIT_CARD_DETAILS';
export const DELETE_CARD = 'DELETE_CARD';
export const MOVE_CARD = 'MOVE_CARD';
export const DELETE_ALL_CARDS_FOR_LISTIDS = 'DELETE_ALL_CARDS_FOR_LISTIDS';